{
 "title": "SystemD Services Status",
 "description": "SystemD services status dashboard for the python script for Telegraf exec plugin.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "service",
    "query": "SHOW TAG VALUES WITH KEY = \"service\""
   },
   {
    "name": "instance",
    "label": "Service",
    "query": "SHOW TAG VALUES FROM \"services_stats\" WITH KEY = \"host\" "
   }
  ]
 },
 "panels": [
  {
   "title": "Global Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "services_stats",
     "query": "SELECT min(\"value\") FROM \"processes_processes\" WHERE (\"host\" =~ /^$host$/ AND \"instance\" =~ /^$instance$/ AND \"type\" = 'ps_count') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Alert(s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_processes",
     "query": "SELECT count(\"status\") FROM \"services_stats\" WHERE (\"host\" =~ /^$host$/) AND \"status\" = 0 AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ps_count" }
     ]
    }
   ]
  },
  {
   "title": "Global Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"status\") * 100 / count(\"status\") FROM (SELECT (\"status\" / \"status\") AS \"status\" FROM \"services_stats\" WHERE \"host\"=~/^$host$/ AND $timeFilter)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monitored hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "services_stats",
     "query": "SHOW TAG VALUES FROM \"services_stats\" WITH KEY = \"host\"",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Monitored services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "services_stats",
     "query": "SHOW TAG VALUES WITH KEY = \"service\"",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Raised Alert(s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "services_stats",
     "query": "SELECT count(\"status\") FROM \"services_stats\" WHERE (\"host\" =~ /^$host$/ AND \"service\" =~ /^$service$/) AND \"status\"= 0 AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Last events",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "processes_processes",
     "query": "SELECT mean(\"status\") FROM \"services_stats\" WHERE (\"host\" =~ /^$host$/ AND \"service\" =~ /^$service$/ ) AND \"status\" = 0 AND $timeFilter GROUP BY time($__interval), \"host\", \"service\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "number" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  { "title": "Global Services Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Services Status",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "status:$tag_host:$tag_service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "services_stats",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "Status History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "STATUS",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 32, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "alias": "$tag_host:$tag_service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "services_stats",
     "query": "SELECT mean(\"status\") FROM \"services_stats\" WHERE (\"host\" =~ /^$host$/ AND \"service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"service\" fill(null)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  }
 ]
}